const cards = [
  'fishAngler1a',
  'fishAngler2a',
  'fishAngler3a',
  'fishDragon1a',
  'fishDragon1b',
  'fishDragon1c',
  'fishViper1a',
  'fishViper1b',
  'fishViper1c',
  'fishViperA',
  'fishViperB',
  'fishViperC',
  'fishLantern1',
  'fishJelly1a',
  'fishJelly1b',
  'fishJelly1c',
  'fishJelly1d',
  'fishJelly2a',
  'fishJelly2b',
  'fishJelly2c',
  'fishJelly2d',
  'fishJelly3a',
  'fishJelly3b',
  'fishJelly3c',
  'fishJelly3d',
  'lightGreen1',
  'lightRed1',
  'lightRed2',
  'lightBlue1',
  'lightBlue2',
  'lightYellow1',
  'lightYellow2',
  'fishJelly4a'
]

export default cards
